// Plain TypeScript imports — no Vite glob tricks, no filesystem reads at runtime.
// The base64 strings are generated by `yarn preprocess` and bundled normally by Vite.
import {
	logo_primary,
	logo_symbol,
	color_palette,
	logo_backgrounds,
	type ReferenceImage
} from '../brand-assets/references.js';

export type { ReferenceImage };

export function loadReferenceImages(): ReferenceImage[] {
	return [logo_primary, logo_symbol, color_palette, logo_backgrounds];
}
